name: mjit_solution
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  lottie: ^3.3.2
  dropdown_button2: ^2.3.9
  animate_do: ^4.2.0
  flutter_animate: ^4.5.2
  fl_chart: ^1.1.1
  image_picker: ^1.2.1
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  table_calendar: ^3.2.0
  op_wifi_utils: ^1.4.2
  pdf: ^3.11.3
  printing: ^5.14.2
  file_picker: ^10.3.10
  webview_flutter: ^4.13.1
  url_launcher: ^6.3.2
  percent_indicator: ^4.2.5
  font_awesome_flutter: ^10.12.0
  device_info_plus: ^12.3.0
  qr_flutter: ^4.1.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# 🔥 IMPORTANT: This MUST be OUTSIDE flutter:
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#1A237E"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png